// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WRLDCWarehouse.Data;

namespace WRLDCWareHouseWebApp.Migrations
{
    [DbContext(typeof(WRLDCWarehouseDbContext))]
    [Migration("20190706164227_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WRLDCWarehouse.Core.Frequency.MartDailyFrequencySummary", b =>
                {
                    b.Property<int>("MartDailyFrequencySummaryId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AverageFrequency")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FVIFrequency")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("MaxBlkFreq")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("MaxFrequency")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("MaxFrequencyTime");

                    b.Property<decimal>("MinBlkFreq")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("MinFrequency")
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("MinFrequencyTime");

                    b.Property<decimal>("NumOutOfIEGCHrs")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("PercGreat50_05")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercGreatEq49_9LessEq50_05")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess48_8")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess49")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess49_2")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess49_5")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess49_7")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PercLess49_9")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("StandardDeviationFrequency")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("MartDailyFrequencySummaryId");

                    b.HasIndex("DataDate")
                        .IsUnique();

                    b.ToTable("MartDailyFrequencySummaries");
                });

            modelBuilder.Entity("WRLDCWarehouse.Core.Frequency.RawFrequency", b =>
                {
                    b.Property<int>("RawFrequencyId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataTime");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("RawFrequencyId");

                    b.HasIndex("DataTime")
                        .IsUnique();

                    b.ToTable("RawFrequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
